name: starter
services:
  starter-devcontainer:
    container_name: starter-devcontainer
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace:rw
    environment:
      AUTH0_DOMAIN: ${AUTH0_DOMAIN:-default-auth0-domain}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE:-default-auth0-audience}    
    command: sleep infinity

